### ISSUE TITLE
conda environment yml

### ISSUE THREAD

**Issue by sherwoac** [BoChenYS/BPnP#1]
thanks for the code.

I'm also a conda fan, glad you use it. why not use a conda environment file like this:
conda env export > bpnp.yml

mine is attached.
[bpnp.zip](https://github.com/BoChenYS/BPnP/files/4282710/bpnp.zip)

then replace the conda steps in your requirements.sh file with:
conda env create -f bpnp.yml

thanks.

adam

**Comment by jonbakerfish** [comment]
Hi @sherwoac , thanks for your suggestion. Using the shell script to set up the environment provides more flexibility. You can install things besides python packages and configure different environment variables etc. However, it's a nice option to have an env YAML file in the repo for other people :)
