### ISSUE TITLE
RunTimeError Fixed

### ISSUE THREAD

**Issue by derbysolto** [BoChenYS/BPnP#12]
Hi,

First of all, I would like to congrats the authors due to such amazing work! I'm a post-graduate researcher.

Recently I faced the same RunTimeError here https://github.com/BoChenYS/BPnP/issues/4

However, I have to use the newest version of PyTorch and Torchvision. So, to fix the error, I've found that setting the saved Tensors as a contiguous tensor, the RunTimeError is fixed.

```
def backward(ctx, grad_output):
    pts2d, P_6d, pts3d, K = ctx.saved_tensors

    pts2d = pts2d.contiguous()
    P_6d = P_6d.contiguous()
    pts3d = pts3d.contiguous()
    K = K.contiguous()
```

I would like to know if is possible to do a Pull Request.

Thanks in advance!

**Comment by BoChenYS** [comment]
Hi, thanks for the fix. Yes, please go ahead with a pull request.
