### ISSUE TITLE
3d vs reprojection error

### ISSUE THREAD

**Issue by htkseason** [BoChenYS/BPnP#16]
Thanks for the wonderful work.
One question on the implementation, `bpnp.py, line 86`
`r = pts2d_i*Si-proj_i[0:2,:]`
This seems to be a 3d error instead of reprojection error, which does not match eq.5 in paper. Could you please provide more details on this? Thanks

**Comment by BoChenYS** [comment]
It's the reprojection error. Normally it would be 
r = pts2d_i - proj_i[0:2,:]/Si
but to make it numerically more stable, we use 
r = pts2d_i*Si - proj_i[0:2,:]
It is still reflecting the reprojection error, not 3d error.
